// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh1KVB1jKuCFaCYQhvrFtoxxueYDAcpW4',
    appId: '1:62265064352:web:f6b83a321d4339a688c2c5',
    messagingSenderId: '62265064352',
    projectId: 'newproject-1557e',
    authDomain: 'newproject-1557e.firebaseapp.com',
    storageBucket: 'newproject-1557e.appspot.com',
    measurementId: 'G-394X31MP6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQNEmGOnxS2DN6Iog03pZh7_6jE0C63kI',
    appId: '1:62265064352:android:8575bbad29a80c7d88c2c5',
    messagingSenderId: '62265064352',
    projectId: 'newproject-1557e',
    storageBucket: 'newproject-1557e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO_g2_dBIyo9V1-nXSU09cMdjTHAskkHk',
    appId: '1:62265064352:ios:f719943c86e4b89788c2c5',
    messagingSenderId: '62265064352',
    projectId: 'newproject-1557e',
    storageBucket: 'newproject-1557e.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO_g2_dBIyo9V1-nXSU09cMdjTHAskkHk',
    appId: '1:62265064352:ios:f719943c86e4b89788c2c5',
    messagingSenderId: '62265064352',
    projectId: 'newproject-1557e',
    storageBucket: 'newproject-1557e.appspot.com',
    iosBundleId: 'com.example.newproject',
  );
}
